FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet tool install dotnet-roundhouse -g --version 1.3.1

WORKDIR .
COPY sql/. ./sql/

ENTRYPOINT [ "rh", "--connectionstring=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=scheduler;Pooling=true", "--connstringadmin=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=postgres;Pooling=true", "--sqlfilesdirectory=sql", "--environmentnames=DEV01", "--databasetype=postgres","--silent","--wt=true" ]